### ISSUE TITLE
Error when running the code following the tutorial

### ISSUE THREAD

**Issue by noob3-3** [endrekrohn/fastws-example#1]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/noob33/python_Projects/fastws-example/api/main.py", line 7, in <module>
    from api.service import service
  File "/home/noob33/python_Projects/fastws-example/api/service.py", line 3, in <module>
    from api.feature_0 import subscribe
  File "/home/noob33/python_Projects/fastws-example/api/feature_0/subscribe.py", line 17, in <module>
    @router.send("subscribe")
     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/fastws/routing.py", line 183, in decorator
    self.add_route(
  File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/fastws/routing.py", line 140, in add_route
    route = Operation(
            ^^^^^^^^^^
  File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/fastws/routing.py", line 66, in __init__
    assert (
AssertionError: Send operations with a response model defined must include a reply

**Comment by endrekrohn** [comment]
> Process SpawnProcess-1: Traceback (most recent call last): File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap self.run() File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started target(sockets=sockets) File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run return asyncio.run(self.serve(sockets=sockets)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve config.load() File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load self.loaded_app = import_from_string(self.app) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string module = importlib.import_module(module_str) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1206, in _gcd_import File "", line 1178, in _find_and_load File "", line 1149, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/home/noob33/python_Projects/fastws-example/api/main.py", line 7, in from api.service import service File "/home/noob33/python_Projects/fastws-example/api/service.py", line 3, in from api.feature_0 import subscribe File "/home/noob33/python_Projects/fastws-example/api/feature_0/subscribe.py", line 17, in @router.send("subscribe") ^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/fastws/routing.py", line 183, in decorator self.add_route( File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/fastws/routing.py", line 140, in add_route route = Operation( ^^^^^^^^^^ File "/home/noob33/.cache/pypoetry/virtualenvs/api-iLUDRhRf-py3.11/lib/python3.11/site-packages/fastws/routing.py", line 66, in **init** assert ( AssertionError: Send operations with a response model defined must include a reply

Hey!
Sorry for the late reply, I took some time off on vacation 😎 

As for your issue:
I've now updated the example project to reflect the changes made in version 0.1.5 and 0.1.6. I think this will sort out your issue of running the project.

I've also added a minimal test suite to make sure the project runs as expected.

Let me know if you have any other issues I can gladly help with - this project is still very unripe 👉
